spring.application.name=springbootdemo
logging.file.path=logs
logging.file.name=${logging.file.path}/${spring.application.name}.log
# logging.logback.rollingpolicy.file-name-pattern=${spring.application.name}-%d{yyyy-mm-dd}
logging.logback.rollingpolicy.max-file-size=10KB

